name:                artificial-general-intelligence
version:             0.1.0.0
github:              "razvan-panda/artificial-general-intelligence"
license:             BSD3
author:              "Răzvan Flavius Panda"
maintainer:          "razvan.panda@gmail.com"
copyright:           "(c) 2019 Răzvan Flavius Panda"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            artificial general intelligence

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/razvan-panda/artificial-general-intelligence#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - placeholders
  - template-haskell
  - hint
  - hedgehog
  - hedgehog-fn

executables:
  artificial-general-intelligence-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - artificial-general-intelligence

tests:
  artificial-general-intelligence-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - artificial-general-intelligence
    - hedgehog
    - hedgehog-fn
